### ISSUE TITLE
Set /ob fly to false by default so it stops causing issues with weighted ranks

### ISSUE THREAD

**Issue by Astolate** [BentoBoxWorld/IslandFly#118]
### Is your feature request related to a problem?

Yes, there are issues when you set /ob fly to false for default rank and /ob fly true to higher groups in luck perms groups, higher can't use the command even if they have both groups set for them.

For example:
default: false, LP weight:1
GroupA: true (inherits from default), LP weight:50
GroupB: not set at all (inherits from default), LP weight:100

If PlayerA has GroupA set to them they can use /ob fly
If PlayerB has GroupA and GroupB set to them they CAN'T use /ob fly

For example:
default: false, LP weight:1
GroupA: true (inherits from default), LP weight:50
GroupB: true (inherits from default), LP weight:100

If PlayerA has GroupA set to them they can use /ob fly
If PlayerB has GroupA and GroupB set to them they still CAN'T use /ob fly

I've already gone over it with the LP discord and they were stumped as to why it does that. Checking perms shows it set to true but it denies the command to the player.

![obflyissue](https://github.com/user-attachments/assets/bc5af5e4-504e-40f1-abb2-1aa196f64fcb)

### Describe the solution you'd like.

Make /ob fly set to false by default so we don't have to set it to false for the lower weighted rank and it won't conflict with higher weighted ranks.

### Describe alternatives you've considered.

Not sure, but open to solutions.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
[IslandFly-1.12.0-SNAPSHOT-LOCAL.jar.zip](https://github.com/user-attachments/files/16737401/IslandFly-1.12.0-SNAPSHOT-LOCAL.jar.zip)
Okay. First, try this build ^^^ where I have changed the default permission setting to false. Let me know if this works for you.

**Comment by tastybento** [comment]
@Astolate I'm planning on making this default in the next release but I'd like you to confirm that this fixes your issue. Does it?
