### ISSUE TITLE
Player cannot fly although is allowed to

### ISSUE THREAD

**Issue by successed** [BentoBoxWorld/IslandFly#13]
I added the player to the man, the player has the authority to fly, but he cannot fly, he warns you that you can fly on your own island, can you correct this?
i have IslandFly addon

server version is 1.14.3
BentoBox-1.6.0-SNAPSHOT-b1267
IslandFly-0.2.0

**Comment by wellnesscookie** [comment]
I had tested on 1.14.3 and all works perfectly.
You need the flybypass permission in order to fly on others people islands.

**Comment by successed** [comment]
> I had tested on 1.14.3 and all works perfectly.
> You need the flybypass permission in order to fly on others people islands.

WHY? i'am in the island team ? i'am the co-owner.

**Comment by wellnesscookie** [comment]
No, still couldn't reproduce it. Been using it for a while and had no problems with this, even when I was the sub-owner.

**Comment by successed** [comment]
> No, still couldn't reproduce it. Been using it for a while and had no problems with this, even when I was the sub-owner.

How did you do that, are you sure it was done?
I can't, how does that happen?

**Comment by successed** [comment]
i download dev version and problem is fixed, 
and new problem here.
if change bskyblock command in config. is fly or new command fly not a workt

**Comment by wellnesscookie** [comment]
Oh yes, I changed code a bit in my PR so it will allow you to use aliases for fly command too. That code was outdated.

**Comment by successed** [comment]
@wellnesscookie is fixed t,y.

**Comment by wellnesscookie** [comment]
I hope @Poslovitch and @tastybento don't mind that I shared my .jar with you.

**Comment by wellnesscookie** [comment]
@Poslovitch #14  fixes it, you can close now.
