### ISSUE TITLE
fly don't work on caveblock

### ISSUE THREAD

**Issue by Robowarrior22** [BentoBoxWorld/IslandFly#15]
### Description
i cant make this work on my caveblock. Whats the command, i cant find it, please help, thanks

#### Steps to reproduce the behavior
- try use fly on caveblock
- no command?

#### Expected behavior
work with caveblock?

#### Server

 - OS: **windows 7**
 - Java version: **java 8**

#### Plugins
```
bentobox, essentialsx
```

##### BentoBox and Addons

```
caveblock
islandfly
```

##### Configuration

 - Database: **JSON**

**Comment by BONNe** [comment]
Yes, it is implemented only in BSkyBlock and AcidIsland.
#14 will allow to run this addon in any gamemode.

**Comment by Robowarrior22** [comment]
id love to use it on my caveblock server. Any ETA?
