### ISSUE TITLE
Auto Fly

### ISSUE THREAD

**Issue by Nedjii** [BentoBoxWorld/IslandFly#17]
Hello, i suggest an auto fly feature, meaning when a player has the permission to fly he doesn't have to run the command, never, there may be a console command that put the player in fly and give the permission so he never have to run it. 
Actually a player has to type the command each time he joins and that can be really annoying.
And when you go to the spawn which is in another world you don't have the fly but you still get the message telling you that your fly will be disabled.
There would be an option in the config telling who can autofly on an island (coop, trust etc),
regards.

**Comment by Nedjii** [comment]
If i remember correctly it was the askyblock fly behavior which was working fine. There was just a permission and no command to be ran by player : askyblock.islandfly

**Comment by Nedjii** [comment]
My dev tried to make it but you trigger island enter event only when the player leave his island then goes back on it flying and it's pretty random.

**Comment by tastybento** [comment]
Hi Nedji - did your dev try to adjust the code of the addon? I'd recommend he try and then submit it as a PR and we can then look at it and find the problem. This addon doesn't have a lot of support right now so it'd be good to have contributions.

**Comment by Nedjii** [comment]
That's someone i pay to make plugins or actually modify what's not going well for me so I fear we wont give it.

**Comment by tastybento** [comment]
Huh. That's surprising. I have a number of test classes to check events are firing when you enter/exit islands and they check out for teleporting (it's exactly the same code as movement). If you can share some case that shows it not working I'd appreciate it.

**Comment by Nedjii** [comment]
On the first screenshot i did /is, i got no message telling me i was entering my island, when we tested for the fly addon i wasn't noticed neither, in the second screenshot i want out my island flying then came back and i got noticed that i was entering my island.
As you can see when the enter island triggers you get the message, when it doesn't you don't get it ...

![2019-08-22_03 39 48](https://user-images.githubusercontent.com/30918460/63479414-8a86c900-c48e-11e9-86ed-b19b66775500.png)
![2019-08-22_03 39 58](https://user-images.githubusercontent.com/30918460/63479422-91add700-c48e-11e9-956e-aa4c1d1bef6c.png)

**Comment by tastybento** [comment]
Okay, yes, I see where the bug is now. Thanks.
