### ISSUE TITLE
Player not can fly in nether and end island

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/IslandFly#29]
#### Describe the bug
Player not can fly in nether and end island
https://streamable.com/tmx2p

When type /is fly in nether or end island. Always say "Fly mod enabled!" But not can.

##### BentoBox Version (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/71115625-68564b00-21e3-11ea-9d14-17c8790c2f8f.png)

#### Plugins (Optional)
![image](https://user-images.githubusercontent.com/47111280/71115646-6db39580-21e3-11ea-85f0-593483825475.png)

**Comment by tastybento** [comment]
What text does the player see when they type `/is fly`? They must see something like not allowed to fly/wrong world/enabled/disabled.

**Comment by tastybento** [comment]
If the player sees "Fly mode enabled!" then the Bukkit API call to set fly mode is working. If he cannot fly then I suspect another plugin is preventing it.

**Comment by tastybento** [comment]
Also, just to check - the player is double tapping space to fly right?

**Comment by OverBrave** [comment]
Yes

**Comment by OverBrave** [comment]
Yes, this is my problem. I tested in test server and work perfectly. But what is problem? Weird.

**Comment by OverBrave** [comment]
Now type "/is fly" saying "fly mode enabled" again type saying "fly mode disabled." 
But still can't fly.

**Comment by OverBrave** [comment]
Very strange sometimes says "flying mode turned on" constantly. Sometimes it says "closed." But he still can't fly.

**Comment by tastybento** [comment]
There must be another plugin preventing fly. I don't know which one, but it could be WorldGuard - there is an option to disable toggling of fly in a region. It might be another one. You'll need to remove them one by one until you find out. Just make a copy of your server and try that.
