### ISSUE TITLE
Permission to bypass flytimeoutside

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/IslandFly#3]
_From @tastybento on July 15, 2017 22:37_

_From @wasder on April 1, 2017 15:35_

I have island fly (via ASB) and global fly (other plugin) for different ranks on my server. 
Players with global fly have to manually activate /fly anytime they leave someone's island.

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#89_

_Copied from original issue: BentoBoxWorld/bentobox#75_

**Comment by Poslovitch** [comment]
_From @tastybento on July 15, 2017 22:37_

_From @Poslovitch on April 1, 2017 15:44_

Will be done for 4.0 ;)

**Comment by Poslovitch** [comment]
_From @tastybento on July 15, 2017 22:37_

@Poslovitch How will you know they have fly with the other plugin?

**Comment by Poslovitch** [comment]
_From @tastybento on July 15, 2017 22:37_

_From @Poslovitch on April 1, 2017 16:21_

I will just do a check for a perm like "x.bypassflylimit", and so the plugin won't remove flymode

**Comment by DarkRails** [comment]
I think this issue has been solved. You can use the "islandfly.bypass" permission to do that.
