### ISSUE TITLE
spectator gamemode problem

### ISSUE THREAD

**Issue by xiko46** [BentoBoxWorld/IslandFly#30]
Hello I find a problem with the /is fly the moderators in spectator lose it on the is of other players and falls to infinity, the addon takes over the essentials permissions among others yet they have the perms:
    - skyblock.island.flybypass
    - skyblock_nether.island.flybypass

**Comment by BONNe** [comment]
there is no permission skyblock.island.flybypass.
[gamemode].island.flybypass is based on gamemode not the world
