### ISSUE TITLE
Fly Permission Not Working

### ISSUE THREAD

**Issue by srrawr11** [BentoBoxWorld/IslandFly#57]
Version: Paper 1.16.5
Java: 1.8

Problem:
There is a problem with the permission.. everyone can run the command, even if you don't have the permission.

**Comment by BONNe** [comment]
Permission is activated (true) by default. 
```
  '[gamemode].island.fly':
    description: Allows access to fly command.
    default: true
```

If you do not want players to have a permission to use a command, you need to negate it:

`-[gamemode].island.fly` where `[gamemode]` is a BentoBox gamemode addon name in lowercase, like `bskyblock` or `caveblock`

**Comment by srrawr11** [comment]
I am using it for AOneBlock.
So who have the permission won't be able to use fly isnt?

**Comment by tastybento** [comment]
Give players who are not allowed to fly this permission:


-aoneblock.island.fly

Note the minus sign at the front!

This **removes** the default permission.

**Comment by srrawr11** [comment]
I have put the permission to my default.yml of LuckPerms.. but as you see is not working
https://i.imgur.com/NlEhTwv.mp4

**Comment by tastybento** [comment]
LuckPerms handles negative permissions different than other plugins like PermissionsEx do.
Instead of adding a - in front of the permission, you need to set the value to false
eg: `/lp group owner permission set some.permission false`

**Comment by srrawr11** [comment]
Got it, thanks for your attention and help, I appreciated :)
It's working.
