### ISSUE TITLE
Players can also fly in other gamemodes

### ISSUE THREAD

**Issue by zermarvt** [BentoBoxWorld/IslandFly#86]
### Expected behavior

Normally when you type /is fly you should only be able to fly on skyblock. But you can also fly with /is fly (if you activate it in skyblock) in oneblock.

### Observed/Actual behavior

See expected behavior

### Steps/models to reproduce

There is no error in the console.

### BentoBox version

Bentobox Version: 1.20.0
IslandFly: IslandFly-1.8.1-SNAPSHOT-b134

### Plugin list

AdvancedCrates, Bentobox, BlockParticles, BungeeTablistPlus, Citizens, CloudNet-Bridge, CMI, CMI-Lib, CommandPanels, CustomOreGen, DailyRewardsPlus, EconomyShopGUI, FastAsyncWorldEdit, HeadDatabase, LuckPerms, PetBlocks, PlaceholderAPI, PlugManX, Quests, QuickShop, ServerRestorer, Vault, WorldBorderAPI, WorldGuard

**Comment by tastybento** [comment]
I can't replicate this right now. I started a server with BSkyBlock and AOneBlock and Island Fly. I started an island in SkyBlock, then I ran `/is fly` and I was able to fly. I then make a block in AOneBlock and typed `/is fly` and I got the error that I was in the wrong world for that:

<img width="851" alt="Screen Shot 2022-03-12 at 9 10 12 AM" src="https://user-images.githubusercontent.com/4407265/158027786-600e05da-d9b1-4eb5-9815-7eb5ac58ef43.png">

Can you share the steps you took to get from SkyBlock to OneBlock?
