### ISSUE TITLE
On Y<0 Using /is fly can't enable flying.

### ISSUE THREAD

**Issue by CuteLittleSky** [BentoBoxWorld/IslandFly#87]
### Expected behavior

Fix it.

### Observed/Actual behavior

On Y<0 Using /is fly can't enable flying.

### Steps/models to reproduce

On Y<0 Using /is fly .

### BentoBox version

Server： PURPUR 1.18.2
BentoBox Version： 1.20.1
DataBase： MYSQL
oneblock_world (OneBlock) 
AOneBlock 1.9.0 (ENABLED)
Border 3.2.0 (INCOMPATIBLE)
Chat 1.1.4 (ENABLED)
ControlPanel 1.13.0 (ENABLED)
IslandFly 1.8.1 (ENABLED)
Level 2.9.0 (ENABLED)
Limits 1.19.0 (ENABLED)
VoidPortals 1.5.0.0 (ENABLED)
Warps 1.11.2 (ENABLED)

**Comment by BONNe** [comment]
This issue should be fixed by https://github.com/BentoBoxWorld/BentoBox/pull/1971
