### ISSUE TITLE
use money or exp to fly

### ISSUE THREAD

**Issue by RAURORA2** [BentoBoxWorld/IslandFly#97]
### Is your feature request related to a problem?

use money or exp to fly

### Describe the solution you'd like.

use money or exp to fly

### Describe alternatives you've considered.

use money or exp to fly

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
I think that would better fit with upgrades addon.

**Comment by RAURORA2** [comment]
>
